### COURSERA, QUIZ

# Q 1
SELECT COUNT(*)
FROM PLANES

# Q 2
SELECT *
FROM PLANES
WHERE SEAT_COUNT >= 100
ORDER BY SEAT_COUNT

# Q 3
SELECT TAIL_NUMBER, COUNT(*)
FROM FLIGHTS
GROUP BY TAIL_NUMBER

# Q 4
SELECT TAIL_NUMBER, SUM(PASSENGER_COUNT) as PASSENGER_ACCROSS_ALL
FROM FLIGHTS
GROUP BY TAIL_NUMBER
HAVING PASSENGER_ACCROSS_ALL > 600

# Q 5
SELECT COUNT(*)
FROM FLIGHTS
WHERE DEPARTURE_AIRPORT IN (
  SELECT AIRPORT
  FROM AIRPORTS
  WHERE COUNTRY in ('US')
)

# BELOW Course Solution, but doesn't work (gave only one line 'IT' ; 50)

SELECT COUNTRY, COUNT(*) AS NUM_FLIGHTS
FROM FLIGHTS f
LEFT JOIN AIRPORTS a
ON f.DEPARTURE_AIRPORT = a.AIRPORT 

# Q 6
SELECT c.REGIONALITY, COUNT(*)
FROM FLIGHTS f
LEFT JOIN CITY_PAIRS c
ON (f.DEPARTURE_AIRPORT = c.DEPARTURE_AIRPORT AND f.ARRIVAL_AIRPORT = c.ARRIVAL_AIRPORT)
GROUP BY c.REGIONALITY
ORDER BY COUNT(*) DESC

# Q 7
SELECT COUNT(*)
FROM CITY_PAIRS
WHERE DEPARTURE_AIRPORT IN ('KLAX', 'KDEN', 'KORD', 'KDET', 'KLGA')

# Q 8
SELECT COUNT(*)
FROM AIRPORTS
WHERE ELEVATION IS NULL

# Q 9
SELECT PASSENGER_COUNT, FLIGHT_NUMBER
FROM FLIGHTS
ORDER BY PASSENGER_COUNT

# Q 10
SELECT AVG(c.DISTANCE)
FROM FLIGHTS f
LEFT JOIN CITY_PAIRS c
ON (f.DEPARTURE_AIRPORT = c.DEPARTURE_AIRPORT AND f.ARRIVAL_AIRPORT = c.ARRIVAL_AIRPORT)
WHERE FLIGHT_NUMBER LIKE 'SKY%'
